# Simple script to generate a text file

def create_file():
    with open('output.txt', 'w') as f:
        f.write('Hello, this is a file generated by a Python script in GitHub Actions!')

if __name__ == "__main__":
    create_file()

