apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-init-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-init-test
  template:
    metadata:
      labels:
        app: multi-init-test
    spec:
      volumes:
        - name: shared-artifacts
          emptyDir: {}

      initContainers:
        - name: init-a
          image: registry.access.redhat.com/ubi8/ubi
          command: ["/bin/bash", "-c"]
          args:
            - mkdir -p /shared/a && echo "feature A" > /shared/a/fileA.txt
          volumeMounts:
            - name: shared-artifacts
              mountPath: /shared

        - name: init-b
          image: registry.access.redhat.com/ubi8/ubi
          command: ["/bin/bash", "-c"]
          args:
            - mkdir -p /shared/b && echo "feature B" > /shared/b/fileB.txt
          volumeMounts:
            - name: shared-artifacts
              mountPath: /shared

        - name: init-c
          image: registry.access.redhat.com/ubi8/ubi
          command: ["/bin/bash", "-c"]
          args:
            - mkdir -p /shared/c && echo "feature C" > /shared/c/fileC.txt
          volumeMounts:
            - name: shared-artifacts
              mountPath: /shared

      containers:
        - name: pause-container
          image: registry.access.redhat.com/ubi8/ubi
          command: ["/bin/bash", "-c"]
          args: ["sleep infinity"]
          volumeMounts:
            - name: shared-artifacts
              mountPath: /tmp/artifacts