#!/bin/bash

# This script will untar all the .tar files in the CMA directory

# Change this to the directory containing your .tar files
directory="/path/to/CMA"

# Change this to the name pattern of the .tar files
name_pattern="*.tar"

# Use find to get a list of .tar files in the directory
tar_files=$(find "$directory" -name "$name_pattern")

# Loop through all .tar files in the list
for file in $tar_files; do
    # Extract the .tar file
    tar -xf "$file" -C "$directory"
    # Remove the .tar file after extraction
    rm "$file"
done

echo "All .tar files in CMA directory have been untarred."
